version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - allow: dependency-updates  # ← Important : autorise les mises à jour

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
